EXCHANGE_NAME = "probit"
MESSAGE_TIMEOUT = 30.0
PING_TIMEOUT = 10.0
WS_URI = "wss://api.probit.com/api/exchange/v1/ws"
AUTH_URL = "https://accounts.probit.com/token"

ERROR_CODES = {
    400: ["INVALID_ARGUMENT", "INVALID_MARKET", "INVALID_CURRENCY", "NOT_ENOUGH_BALANCE", "DUPLICATE_ADDRESS", "INVALID_ORDER", "NOT_ALLOWED_COMBINATION"],
    401: "UNAUTHORIZED",
    403: "TOO_MANY_OPEN_ORDERS",
    429: "RATE_LIMIT_EXCEEDED",
    503: ["TRADING_UNAVAILABLE", "MARKET_UNAVAILABLE"]
}
